[package]
name = "language_battles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
num-traits = "0.2.15"
smart-read = "0.9.0"
